apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
  namespace: dev
data:
  FLASK_ENV: "development"
  BACKEND_APP_SETTINGS: "app.config.DevelopmentConfig"
  WEBSOCKET_APP_SETTINGS: "app.config_socket.DevelopmentConfig"
  POSTGRES_DB: "chatdb"
  DB_HOST: "postgres"
  REACT_APP_BACKEND_SERVICE_URL: "http://backend:5004"
  REACT_APP_WEBSOCKET_SERVICE_URL: "http://websocket:5001"
  NODE_ENV: "development"
