apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: dev
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "verysecurepassword"
  SECRET_KEY: "topsecretkey123"
  DATABASE_URL: "postgresql://postgres:verysecurepassword@postgres:5432/chatdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: prod
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "verysecurepassword"
  SECRET_KEY: "topsecretkey123-production"
  DATABASE_URL: "postgresql://postgres:verysecurepassword@postgres:5432/chatdb"