global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'chatapp-backend'
    static_configs:
      - targets: ['backend:5006']
        labels:
          service: 'backend'
    
  - job_name: 'chatapp-websocket'
    static_configs:
      - targets: ['websocket:5001']
        labels:
          service: 'websocket'